@startsalt
{
  {^"Заказы"
    Статус | [ Все ^]
    Дата с | "01.09.2026"
    Дата по | "30.09.2026"
    [Найти]
    {#
      ID | Клиент | Услуга | Дата | Статус
      8f21... | Иван | Химчистка | 10.09 | Новый
      2bc4... | Анна | Клининг | 11.09 | Назначен
    }
    [Открыть карточку]
  }
}
@endsalt
