@startsalt
{
  {^"Создание заказа"
    Вид услуги | [ Химчистка          ^]
    Имя | "Иван"
    Телефон | "+79990000000"
    Адрес | "Москва, улица, дом"
    Желаемое время | "10.09.2026 14:00"
    Комментарий | "Диван, 3 места"
    Предварительная цена | 5 000 рублей
    [Создать заказ]
  }
}
@endsalt
