@startsalt
{
  {^"Расписание мастера"
    Дата | [ 10.09.2026 ^]
    {#
      Время | Услуга | Адрес | Статус
      10:00 | Химчистка | Ленина, 10 | Подтверждён
      14:00 | Дезинсекция | Мира, 5 | Новый
    }
    [Открыть заказ] | [Начать работу] | [Завершить]
  }
}
@endsalt
